// --------------------------------------------------------------------------------------------------------------------
// <copyright company="PVWI Family" file="201412240235055_InicialTables.Designer.cs">
//   Todos os direitos reservados.
// </copyright>
// <auto-generated />
// --------------------------------------------------------------------------------------------------------------------
namespace PVWI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    /// <summary>
    /// The inicial tables.
    /// </summary>
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class InicialTables : IMigrationMetadata
    {
        /// <summary>
        /// The resources.
        /// </summary>
        private readonly ResourceManager Resources = new ResourceManager(typeof(InicialTables));

        /// <summary>
        /// Gets the id.
        /// </summary>
        string IMigrationMetadata.Id
        {
            get { return "201412240235055_InicialTables"; }
        }

        /// <summary>
        /// Gets the source.
        /// </summary>
        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        /// <summary>
        /// Gets the target.
        /// </summary>
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
