// <auto-generated />
namespace PVWI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Atualizacaodasentidadesecriacaodatabelafaturas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Atualizacaodasentidadesecriacaodatabelafaturas));
        
        string IMigrationMetadata.Id
        {
            get { return "201501012301581_Atualizacao das entidades e criacao da tabela faturas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
